source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'FSPhotoBrowser_Example', :exclusive => true do
  pod "FSPhotoBrowser", :path => "../"
end

target 'FSPhotoBrowser_Tests', :exclusive => true do
  pod "FSPhotoBrowser", :path => "../"

  
end
